### ISSUE TITLE
measure_power capability for powernode-6 nodes not reporting anymore since 0.10.0

### ISSUE THREAD

**Issue by jghaanstra** [athombv/com.greenwavesystems#10]
**What is your Homey version (Settings → System)?**
firmware 0.10.0 / greenwave app 1.0.4

**What did you try to achieve?**
Use the current energy consumption of a multichannel node of the Greenwave powernode-6 in Insights and as flow trigger. This worked on version 0.9.3 and Greenwave app version 1.0.4.

**Please include detailed steps how we can reproduce the issue**
Just pair any powernode-6 and check Insights for any of the multichannel nodes. It does not update the energy measure.

**Any other remarks**
This does work for the powernode-1 which is pretty much the same driver except for the multichannel part. So it seems to be related to that. I also noticed that the UI is sometimes reporting and incorrect on/off status for a multichannel powernode-6. I'll look into this further but might report that as a seperate bug.

**Comment by jghaanstra** [comment]
Someone on Slack pointed out to me that setting all association groups to 1 fixes this and it seems that does indeed do the trick. On firmware prior to 0.10.x this was not necessary but now it does. The lousy documentation of the Greenwave Powernodes suggests setting association group 3 to 1 should be sufficient to get current power measures back.

I'll make a pull request if I can find the time for it and Athom does not beat me to it.

**Comment by RobinBol** [comment]
Updated the app with fix (v1.0.4).
