### ISSUE TITLE
setting keep_alive_time to high level gives error "value is out of bounds"

### ISSUE THREAD

**Issue by kasteleman** [athombv/com.greenwavesystems#11]
Ï try to set the keep alive time of the greenwave powernode 6 to value 200.
I run the app from the commandline in debug mode. If i set the value to 20, it reports back that it has been set to 200. On the other hand if i set the value to 200 it returns "value is out of bounds".
The size off the setting should be 1, but if i change it to size 2, the errors are gone and i can set the setting without any error. Is this a bug in the greenwave, or is this a zwave implementation error?

**Comment by caseda** [comment]
when running debug what buffer value is being send (shows at the bottom in "newValue:")
when you use 20 and 200 as the values,
looking at your reaction about the value of 20 it looks like the value is being multiplied by 10 for some reason.
The max it should be able to handle = 255,
200*10 = 2000
way above the 255 so you will get value out of bounds

**Comment by kasteleman** [comment]
Indeed, it seems that it is multiplied with 10 and that the crash after +/- 2 days is related because the error it throws at the following line in the zwave driver :

this.driver.settings.forEach(settingsId => {

**Comment by caseda** [comment]
try using a (temporary) parser, see if it will still happens afterwards:
"parser": value => {
	value = Math.round(value / 10);
	return new Buffer([value]);
}
