### ISSUE TITLE
Unable to disable the polling interval (set interval to 0)

### ISSUE THREAD

**Issue by TedTolboom** [athombv/com.greenwavesystems#15]
I have a number of sub-nodes that are not being used for the time being.
To avoid excessive (un-needed) polling, I tried to set the polling interval to 0 (disabling polling).

Unfortunately, this setting (polling interval to 0) is not supported (unable to save; button greyed out), see below screenshot:
<img width="600" alt="schermafbeelding 2016-10-27 om 10 04 34" src="https://cloud.githubusercontent.com/assets/17163431/19759409/2e89966e-9c2d-11e6-9af0-896c071cf90e.png">

Can this be implemented in next update?

**Comment by RobinBol** [comment]
Good suggestion. Will look at it!
