### ISSUE TITLE
Remove `singleChannelNode`

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/com.greenwavesystems#16]
What is this property? :-)

**Comment by RobinBol** [comment]
Good question, seems it was added by a PR of Jelger Haanstra, probably doesn't do anything:p

**Comment by jghaanstra** [comment]
It actually was part of the initial Greenwave Powernode-1 driver which came from Webster: https://github.com/spikerm/Powernode-1-homey .

I just forked his repository and eventually made a PR to get the Greenwave Powernode-1 driver added into the Athom app, Did that after adding some other stuff like the keep alive time setting. Not sure how Webster came to use the singleChannelNode. Always figured someone from Athom told him to do so :-)
