### ISSUE TITLE
No consistent energy readings from Greenwave powernodes after firmware upgrade 1.0.1

### ISSUE THREAD

**Issue by jghaanstra** [athombv/com.greenwavesystems#19]
**What is your Homey version (Settings → System)?**
firmware 1.0.2 / Greenwave Systems app 1.0.6

**What did you try to achieve?**
Use the current power usage from a Greenwave Powernode 1 or 6 socket as a trigger in flows.

**What was the result?**
Flows are not triggered even though I know the energy usage of the socket has changed (for instance when turning off the TV) and when looking at the device card there are mostly no energy readings.

Some devices show no energy readings at all.
![chrome_2016-11-22_22-43-02](https://cloud.githubusercontent.com/assets/4710062/20543122/0c61952c-b105-11e6-874e-b0a7a618bb4c.png)

Some device show only the cumulative energy usage but still not the current usage.
![chrome_2016-11-22_22-53-39](https://cloud.githubusercontent.com/assets/4710062/20543555/89c82f3e-b106-11e6-93d3-9da3245c7683.png)

And some devices only show the current usage but no cumulative energy usage. And I have one Powernode-1 that shows both cumulative and current energy usage.

**What did you expect as result?**
Consistency in showing both cumulative and current energy usage. This worked great on 0.10.9 after adding the right group associations so I'd expected it to work on 1.x as well and where it would update the energy readings at the given polling interval.

**Any other remarks**
I have already tried reinstalling the app, flipping settings, flipping device group associations. It just does give me consistent results. I asked on the forum and I seem to be the only one with the problem.

Here is a log, perhaps it helps: D0FAC6068E

**Comment by uNiiek** [comment]
Same issue for me:
Log: 4A664B10E7

![naamloos](https://cloud.githubusercontent.com/assets/18580351/20688046/613a828e-b5bf-11e6-84e8-1a060723ff1d.png)
![naamloos2](https://cloud.githubusercontent.com/assets/18580351/20688048/63c4b420-b5bf-11e6-81d0-b0a06f439bda.png)

**Comment by msprenger** [comment]
This happens to me too, seems to be totally random, some devices show no readings at all, others show energy and other show the meter.

**Comment by jghaanstra** [comment]
I just updated to firmware version 1.0.3 and this seems to have fixed this issue. It was confirmed by someone else on Slack so I'll close this issue for now.
