### ISSUE TITLE
SW 1.0.4 (GW app 1.0.8) Polling interval missing on multichannel nodes

### ISSUE THREAD

**Issue by TedTolboom** [athombv/com.greenwavesystems#22]
With the update to SW 1.0.4 the settings section of the multichannel nodes have been removed.
I understand this for the device specific parameters, which are in majority linked to the main node.

Consequence of this removal is that also the polling interval is not available anymore on the multichannel nodes. Now only 1 polling frequency can be selected; which will be the minimum polling interval of all sockets

This is however not a device parameter, but software trigger from Homey.
This differentiation of different polling intervals is enabling traffic relaxation for sockets which are not relevant to poll frequently (e.g. no flows connected to it).

Please re-add the polling interval to the multichannel nodes or advise how to make the required changes in the app.json / driver.js

**Comment by TedTolboom** [comment]
Would it be possible to add a specific settings section to the multichannel nodes, instead of duplicating the settings of the main node?

Like:
```
"multiChannelNodes": {
					"1": {
						"class": "socket",
						"capabilities": [
							"onoff",
							"measure_power",
							"meter_power"
						],
						"settings": [
						{
						"id": "poll_interval",
						"type": "number",
						"attr": {
							"min": 0,
							"max": 3600
							}
						}
						],
```

**Comment by RobinBol** [comment]
For now this is not possible, the app currently polls the multichannels at the same time, this should not cause any issues as 6 requests/responses are not quite stressing the z-wave network.

**Comment by msprenger** [comment]
Does this mean this will not be implemented in the Greenwave app? (since the issue is closed). Once the Greenwave / Homey combination gets more stable i wouls really like the ability to set a polling interval on the individual multichannel nodes...

**Comment by RobinBol** [comment]
Well, what would be your use case for that?

**Comment by msprenger** [comment]
I think it would be interesting to disable polling on all individual multichannel nodes where i am not interested in energy readings, e.g. my lights connected. Also having a pretty small polling interval on my laundry machine (every 20 seconds), which could be running on the same Greenwave 6 device.

Since i have 7 Greenwave 6 nodes that would mean polling 36 devices.. which could be dangerously close to stressing the Z-wave network...

**Comment by TedTolboom** [comment]
Agree with @msprenger 

I currently have 5 powernode-6's.. most of the devices I could see a benefit on frequent polling intervals... but the spare sockets I also use as "regular socket" for e.g. a charger or ir repeater... for which it does not make sense to log.

**Comment by TedTolboom** [comment]
@RobinBol What is the plan to implement this for multichannel nodes?

**Comment by RobinBol** [comment]
Currently there is no concrete plan for this, if you have suggestions be welcome to work them out (homey-zwavedriver) or post them here.

**Comment by RobinBol** [comment]
Fixed
