### ISSUE TITLE
SW 1.0.4 (GW app 1.0.8 + PR #23) Default config not added to device during interview; unable to add value 255

### ISSUE THREAD

**Issue by TedTolboom** [athombv/com.greenwavesystems#24]
Homey SW 1.0.4, Greenwave  app v1.0.8 + PR #23 

In the Greenwave app v1.0.8 (without PR#23), the default configuration of a power-node that is going to be added to Homey is defined as:

```
"defaultConfiguration": [
					{
						"id": "keep_alive_time",
						"size": 1,
						"value": 255
					}
				]
```
Since the ID is set as a string, this item will not be parsed during the addition of the device and the device will still be at the default setting of 2 minutes.

Since also the value of "keep_alive_time" in settings is set as 255, saving settings with or without another parameter change will not trigger an update of this parameter to 255 
```
{
					"id": "keep_alive_time",
					"type": "number",
					"attr": {
						"min": 1,
						"max": 255
					},
					"value": 255,
					"label": {
						"en": "Keep Alive Time",
						"nl": "Keep Alive Time"
					},
					"hint": {
						"en": "The amount of minutes without contact between controller and device before the device starts blinking green.",
						"nl": "Aantal minuten zonder contact tussen controller en apparaat voordat het apparaat groen gaat knipperen."
					}
				}
```

Debug log:
```
[debug] settings() newSettingsObj { poll_interval: 300,
  keep_alive_time: 255,
  State_power_loss: '2',
  LED_network: true,
  power_change_percentage: 50 } oldSettingsObj { poll_interval: 300,
  keep_alive_time: 255,
  State_power_loss: '2',
  LED_network: false,
  power_change_percentage: 50 } changedKeysArr [ 'LED_network' ]
```

Only working containment is to update the setting to e.g. 100, save it and update it back to 255.

In Pull request #23 I've updated the default config to be based on integer ID's (on suggestion of @RobinBol ).
```
"defaultConfiguration": [
					{
						"id": 0,
						"size": 1,
						"value": 80
					},
					{
						"id": 1,
						"size": 1,
						"value": 120
					}	
				]
```

Yet it is not possible to set "id": 1 (Keep_alive_time) to the desired 255 in the defaultConfiguration section. If this is done, the add device wizard will stall during the Add custom configuration settings for this app step... Highest value I could determine is 120 (minutes). PR #23 is therefore based on this value; as defaultConfiguration as well as settings section.

Most likely, the values from the defaultConfiguration are either not parsed or incorrectly parsed during this step.

Please correct so that the default configuration can be set to the desired 255 minutes

**Comment by RobinBol** [comment]
It seems the defaultConfig parameters are saved as signed instead of unsigned integers, this will be fixed in a coming Homey firmware update, will close this issue as it is not specific to this app.

**Comment by TedTolboom** [comment]
@RobinBol can you indicate in which Homey firmware update this will be released or should I file another issue at https://github.com/athombv/homey/issues/?

**Comment by RobinBol** [comment]
v1.0.5, already fixed by Emile!
