### ISSUE TITLE
Power usage

### ISSUE THREAD

**Issue by filoor** [athombv/com.greenwavesystems#3]
Power usage wont refresh it stays on the same value

**Comment by jeroenvollenbrock** [comment]
@filoor 
Can you check the associations of the main device?

**Comment by JPe2** [comment]
The power usage is now (Homey 0.9.2) presented in **Wh** and not in **Watt** as it was before (Homey 0.8.xx)
For me, and many others, this is useless now, I need momentairely power use in **Watt**

**Comment by RobinBol** [comment]
Both the powernode 1 and 6 support both momentary Watt readings, as accumulated kWh readings. This should fix the problems mentioned above, if not please let me know.
