### ISSUE TITLE
Greenwave sockets

### ISSUE THREAD

**Issue by dd3uk** [athombv/com.greenwavesystems#31]
I have just purchased a bunch of greenwave sockets. Added the app, checked the switch is on black and then follow instructions to pair, the device is detected then  homey stops responding will come up and the device pairing fails. Homey has crashed whilst trying to pair the devices using the app..... 

tried rebooting homey and trying again but no better.

Invested in a bunch of these on the basis homey supports them so hoping this is going to be a simple bug to fix.....(running latest software and can send in the crash report if needed just ask)

**Comment by RobinBol** [comment]
Hi! What Homey firmware version are you using? What was the exact error message that was displayed when the pairing process failed? Could you describe the setup of your Z-Wave network (number of devices, distance to the greenwave sockets, etc)?

**Comment by RobinBol** [comment]
Will close this issue due to inactivity. If you find this issue at a later moment in time and still encounter this issue, please let us know.

For others, there is a large Z-Wave bug fix release coming up which should also improve the inclusion process of Z-Wave devices.
