### ISSUE TITLE
Homey 0.9.3 / app 1.0.2: Unable to save settings

### ISSUE THREAD

**Issue by TedTolboom** [athombv/com.greenwavesystems#7]
After new install on 0.9.3 I was able to successfully add the 3 Greenwave powernode 6's.

After update to v1.0.2 of the Greenwave systems app, I'm no longer able to save / update the settings (on all powernodes).

<img width="624" alt="schermafbeelding 2016-09-13 om 22 43 27" src="https://cloud.githubusercontent.com/assets/17163431/18490720/8aaacea0-7a03-11e6-82b8-ae6ffd23a6a8.png">

The option is greyed out.

Any suggestions to resolve? Rebooting Homey did not solve it; disabling the app and re-enabling it also not

**Comment by WeeJeWel** [comment]
Looks like there's an invalid setting somewhere. Please check the collapsed items?

**Comment by TedTolboom** [comment]
Fast response Emile, thanks...
<img width="628" alt="schermafbeelding 2016-09-13 om 22 49 03" src="https://cloud.githubusercontent.com/assets/17163431/18490902/559842a0-7a04-11e6-9068-a57b48015eff.png">
Association groups are indeed marked as red; although I did not change it...

Group 1 should be 1 right?

**Comment by WeeJeWel** [comment]
That's pretty odd that it changed suddenly! Change it to 1 and everything should be fine :)

**Comment by TedTolboom** [comment]
Perhaps the dust on top of Homey influenced some bits... 
did not have the time to take care of Homey over the last months and follow/test all intermediate versions. 0.9.3 seems like a big step though...

Updated to association groups to 1 and indeed was able to save the settings.
Keep open to see if issue reoccurs or close the issue based on containment / incident?

**Comment by WeeJeWel** [comment]
Let's close it for now, if it happens, please let me know!
