### ISSUE TITLE
Polling Greenwave devices too often can make the zwave network inoperable

### ISSUE THREAD

**Issue by jghaanstra** [athombv/com.greenwavesystems#8]
**What is your Homey version (Settings → System)?**
0.9.3 (Greenwave Systems app version 1.0.3)

**What did you try to achieve?**
Use the zwave network.

**Please include detailed steps how we can reproduce the issue**
I had been using a local version of the Greenwave app for some time where I set the polling frequency quite high (5 minutes) with a small variation per device to spread the load on the network. This was working pretty well. After installing the app store version one of the device settings was lost and polling was set back to the default 2 minutes.

**What was the result?**
The zwave network had become extremely unstable since the update to version 1.0.3 of the Greenwave app and the polling of one of my Greenwave devices every 2 minutes. Sometimes zwave works after a reboot but it's only a matter of hours before the zwave network becomes inoperable. I can see the devices and use the UI to switch but the devices are not actually switching and the status isnt changed in the UI after re-opening the device card. It's worse for devices that depend on the mesh network where the devices that have a direct connection with the controller can be switched while devices that depend on mesh can not.

**What did you expect as result?**
It would be nice that polling of at least every two minutes would not do the zwave network performance any harm.

**Any other remarks**
I have changed the polling frequency of the device that had lost it's settings back to the +/- 5 minutes polling frequency and the problem is resolved.

**Comment by TedTolboom** [comment]
I have the same issue with my three powernode-6's connected to Homey, after updating to 1.0.3 version of the greenwave app.

Although I've setup the keep-alive setting to 255 minutes.. within 15 minutes the powernode is in the green lights blinking state.

**Comment by jghaanstra** [comment]
I have updated the issue. It seems to be unrelated to version 1.0.3 of the Greenwave app but is caused by polling the Greenwave devices to often. With a polling frequency of at least 5 minutes and variation in frequency between devices to spread the load the zwave network is working fine.

So that seems to be a proper workaround but it would be great if the lower polling frequencies would be possible as well.

**Comment by TedTolboom** [comment]
Thanks for the update.
How many powernode 6's do you currently have connected to Homey?
And what is the spread that you applied (only on de main node or also on all sub-nodes)?

I already had updated the main nodes to a polling interval of 5 minutes (under the assumption that the sun-nodes would follow)... but this did not solve the instability..

I will give it a try with also updating the sub-nodes.

**Comment by jghaanstra** [comment]
I have two powernode-6 and two powernode-1 devices. I use polling times of
around 5 minutes with a 5 second spread between devices. For the
powernode-6 devices you need to set the polling frequency seperatly for
every multichannel node. Make sure you do not change the keep alive time on
the multichannel node as this will cause a crash (this parameter can only
be set on the main node).

2016-09-21 6:08 GMT+02:00 dT <notifications@github.com>:

**Comment by TedTolboom** [comment]
I'm able to change the main nodes to 900 seconds polling interval...
But if I try to change the polling interval of one of the multichannel nodes... the driver is crashing:
<img width="627" alt="schermafbeelding 2016-09-21 om 21 00 39" src="https://cloud.githubusercontent.com/assets/17163431/18725001/de66d3ae-803e-11e6-9679-48f14d589fb5.png">

With the following error message:
<img width="644" alt="schermafbeelding 2016-09-21 om 21 01 10" src="https://cloud.githubusercontent.com/assets/17163431/18725019/ec4b8ba4-803e-11e6-975a-cb2351629525.png">
Consistent for multiple power nodes..

Did you only change the polling interval of existing power nodes or remove and re-add the power nodes?

**Comment by TedTolboom** [comment]
Is there any progress on this issue? @RobinBol ?
My power nodes are still useless (not able to update the sub-note polling interval)..

**Comment by TedTolboom** [comment]
After removing the Powernodes, re-installing the app and re-adding the Powernodes, with keep alive @ 255 and polling interval distributed over the various nodes, my setup (3x PN-6 and 1x PN-1) runs stable

**Comment by RobinBol** [comment]
@jghaanstra could you also confirm this issue has been resolved for you?

**Comment by jghaanstra** [comment]
My zwave chip became inoperable yesterday, probably directly after the
Greenwave systems app was updated. But other than that and with high
polling values of at least 5 minutes per socket my zwave network is stable.

The current default polling is set to 2 minutes. This might still be to low
as I have seen reports that people had problems with this value. The
easiest fix for this issue is to raise the default polling value to 300.
The best fix would be to investigate if performance can be improved to
allow lower polling values.

But in fine with closing the issue. I'm not gonna test with lower polling
values anymore, I don't need them and don't wanna brake something that
currently isn't broken.

Op 27 okt. 2016 10:49 a.m. schreef "Robin Bolscher" <
notifications@github.com>:

**Comment by TedTolboom** [comment]
Robin,

In order to make the GreenWave app idiot proof, I would recommend changing the default settings (when adding a new device) to: polling 300 or 900 seconds and keep alive to 255

This should work in most cases... and if people would like to have a faster polling interval at a certain sub-node, they can adapt the value.

**Comment by RobinBol** [comment]
@TedTolboom, thanks for the suggestion, just changed the default values.

**Comment by RobinBol** [comment]
@TedTolboom, thanks for the suggestion, just changed the default values.

**Comment by RobinBol** [comment]
@TedTolboom, thanks for the suggestion, just changed the default values.
